services:
  kong:
    image: kong/kong-gateway:3.9
    container_name: kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml  # use declarative config
      KONG_PROXY_LISTEN: 0.0.0.0:8000  # Proxy Port
      KONG_ADMIN_LISTEN: 0.0.0.0:8001  # Admin Port
    ports:
      - "8000:8000"  # API Gateway Port
      - "8001:8001"  # Admin API Port
      - "8443:8443"  # HTTPS Proxy
    volumes:
      - ./config:/usr/local/kong/declarative  # Mount kong.yml
    networks:
      - rota-network
    depends_on:
      - rota-api  # Kong wait Go API run first

  rota-api:
    build: .
    container_name: rota-api
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=rota
      - DB_USER=rota_local_user
      - DB_PASSWORD=rota_local_pass
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=rota_redis_local_pass
      - REDIS_DB=0
      - JWT_SECRET=your-secret-key
      - JWT_ACCESS_TOKEN_TTL=24h
      - JWT_REFRESH_TOKEN_TTL=168h
    expose:
      - "3000"  # listen in Docker network
    volumes:
      - ./:/app  # Mount project
    networks:
      - rota-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=rota_local_user
      - POSTGRES_PASSWORD=rota_local_pass
      - POSTGRES_DB=rota
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - rota-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rota_local_user -d rota"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    command: redis-server --requirepass rota_redis_local_pass --appendonly yes  # Enable password and persistence
    networks:
      - rota-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "rota_redis_local_pass", "ping"]  # Add password to healthcheck
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  rota-network:
    driver: bridge

volumes:
  kong_data:
    driver: local