_format_version: "2.1"
_transform: true

services:
  - name: rota-api-service
    url: http://rota-api:3000
    routes:
      - name: public-routes
        paths:
          - /api/v1/routes
          - /api/v1/stations
        strip_path: false
      - name: auth-route
        paths:
          - /api/v1/auth
        strip_path: false
      - name: protected-route
        paths:
          - /api/v1/favorites
          - /api/v1/user
        strip_path: false
        plugins:
          - name: jwt
            config:
              secret_is_base64: false
              key_claim_name: kid
              claims_to_verify:
                - exp
                - nbf
              header_names:
                - Authorization
    plugins:
      - name: cors
        config:
          origins:
            - http://localhost:3000
          methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          headers:
            - Content-Type
            - Authorization
          exposed_headers:
            - Authorization
          credentials: true
          max_age: 3600
      - name: rate-limiting
        config:
          minute: 60
          hour: 1000
          policy: local

consumers:
  - username: frontend
    jwt_secrets:
      - algorithm: HS256
        secret: rota_jwt_secret_key_2024_secure
        key: frontend-key

  - username: mobile-app
    jwt_secrets:
      - algorithm: HS256
        secret: rota_jwt_secret_key_2024_secure
        key: mobile-key