_format_version: "2.1"
_transform: true

services:
  - name: rota-api-service
    url: http://api:3000
    routes:
      - name: public-routes
        paths:
          - /api/v1/routes
          - /api/v1/stations
          - /api/v1/staff
          - /api/v1/health
        strip_path: false
      - name: auth-route
        paths:
          - /api/v1/auth
        strip_path: false
      - name: protected-route
        paths:
          - /api/v1/favorites
          - /api/v1/users
          - /api/v1/vehicles
          - /api/v1/schedules
          - /api/v1/schedule-logs
        strip_path: false
        # ปิดการใช้งาน JWT plugin ชั่วคราวเพื่อการทดสอบ
        # plugins:
        #   - name: jwt
        #     config:
        #       secret_is_base64: false
        #       claims_to_verify:
        #         - exp
        #       header_names:
        #         - Authorization
    plugins:
      - name: cors
        config:
          origins:
            - "*" # Allow all origins for development
          methods:
            - GET
            - POST
            - PUT
            - DELETE
            - PATCH
            - OPTIONS
          headers:
            - Content-Type
            - Authorization
            - Accept
            - Origin
            - X-Requested-With
          exposed_headers:
            - Authorization
            - Content-Length
          credentials: true
          max_age: 3600
      - name: rate-limiting
        config:
          minute: 60
          hour: 1000
          policy: local

consumers:
  - username: frontend
    jwt_secrets:
      - algorithm: HS256
        secret: rota_jwt_secret_key_2024_secure
        key: frontend-key

  - username: mobile-app
    jwt_secrets:
      - algorithm: HS256
        secret: rota_jwt_secret_key_2024_secure
        key: mobile-key