basePath: /
definitions:
  database.Bookmark:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      name:
        type: string
      updatedAt:
        type: string
      url:
        type: string
    type: object
  fiber.Map:
    additionalProperties: true
    type: object
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
host: localhost:3000
info:
  contact: {}
  description: This is a sample server for a rota application.
  title: Rota API
  version: "1.0"
paths:
  /api/bookmark:
    get:
      consumes:
      - application/json
      description: Get all bookmarks
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/database.Bookmark'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: Get all bookmarks
      tags:
      - bookmarks
    post:
      consumes:
      - application/json
      description: Save a new bookmark
      parameters:
      - description: Bookmark
        in: body
        name: bookmark
        required: true
        schema:
          $ref: '#/definitions/database.Bookmark'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/fiber.Map'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: Save a new bookmark
      tags:
      - bookmarks
swagger: "2.0"
